name: on-ui-staging-merge
on:
  push:
    branches:
      - 'staging'
    paths:
      - 'ui/**'
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
  
    - run: yarn install

name: on-ui-main-merge
on:
  push:
    branches:
      - 'main'
    paths:
      - 'ui/**'
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
  
    - run: yarn install

name: on-admin-staging-merge
on:
  push:
    branches:
      - 'staging'
    paths:
      - 'admin/**'
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
  
    - run: yarn install

name: on-admin-main-merge
on:
  push:
    branches:
      - 'main'
    paths:
      - 'admin/**'
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
  
    - run: yarn install

name: on-admin-staging-merge
on:
  push:
    branches:
      - 'staging'
    paths:
      - 'admin/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
  
    - run: yarn install

name: on-admin-main-merge
on:
  push:
    branches:
      - 'main'
    paths:
      - 'admin/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
  
    - run: yarn install
